### ISSUE TITLE
请问能支持一下国家吗？

### ISSUE THREAD

**Issue by JandenMa** [uiwjs/province-city-china#13]
请问能在省之前支持一下国家吗？然后选中中国进入省市区联动，选择其他国家暂时只要选国家就行。

**Comment by jaywcjlove** [comment]
@JandenMa 哪里有标准的国家数据，可以支持。

**Comment by JandenMa** [comment]
> @JandenMa 哪里有标准的国家数据，可以支持。

看下这个可以吗？🤣
http://www.shouce.ren/tool/shujuku

**Comment by jaywcjlove** [comment]
@JandenMa  https://zh.wikipedia.org/zh-cn/%E5%9B%BD%E5%AE%B6%E5%9C%B0%E5%8C%BA%E4%BB%A3%E7%A0%81 这个准确不？

**Comment by jaywcjlove** [comment]
国家和地区代码列表（下载）  
http://www.mohrss.gov.cn/SYrlzyhshbzb/zhuanti/jinbaogongcheng/Jbgcbiaozhunguifan/201112/t20111206_47429.html

**Comment by JandenMa** [comment]
> @JandenMa https://zh.wikipedia.org/zh-cn/%E5%9B%BD%E5%AE%B6%E5%9C%B0%E5%8C%BA%E4%BB%A3%E7%A0%81 这个准确不？

谨慎敏感地区，哈哈哈

**Comment by jaywcjlove** [comment]
@JandenMa 已经有国家数据了 `+ province-city-china@6.1.0`

**Comment by JandenMa** [comment]
> @JandenMa 已经有国家数据了 `+ province-city-china@6.1.0`

非常感谢！
