### ISSUE TITLE
可否加入经纬度信息

### ISSUE THREAD

**Issue by Psli** [uiwjs/province-city-china#15]
参考 https://github.com/kakuilan/china_area_mysql 的中的经纬度信息

**Comment by jaywcjlove** [comment]
@Psli 金纬度数据哪里搞？能否给比较官方的数据呢？

**Comment by Psli** [comment]
高德取省市县；腾讯取区县以下

**Comment by Psli** [comment]
@jaywcjlove 参考下这里 https://github.com/kakuilan/china_area_mysql/issues/21

**Comment by jaywcjlove** [comment]
@Psli 每个地图经纬度都不一样，以哪个为准呢？

- `<AMap`
- `<Baidu`
- `<MapBar`
- `<MapABC`
- `<SoSoMap`
- `<AliYun`
- `<Google`
- `<GPS`

https://github.com/uiwjs/react-native-amap-geolocation/blob/303b42d65051719bdb973818a0ef64f106941232/index.d.ts#L185-L192

**Comment by Psli** [comment]
看看有没有其他人有需求，暂时关闭
