### ISSUE TITLE
缺湖北省 > 省直辖县级行政区划 > 	仙桃市、潜江市、天门市、神农架林区

### ISSUE THREAD

**Issue by fjc0k** [uiwjs/province-city-china#18]
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/42.html
![image](https://user-images.githubusercontent.com/13151189/105623303-aba5d300-5e53-11eb-92da-f3469f647c11.png)

http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/42/4290.html
![image](https://user-images.githubusercontent.com/13151189/105623311-b7919500-5e53-11eb-8788-40449887b4d8.png)

**Comment by jaywcjlove** [comment]
@fjc0k 数据不缺，你搜索一下这里面有

https://raw.githubusercontent.com/uiwjs/province-city-china/gh-pages/data.sql

- 429004000000  仙桃市
- 429005000000  潜江市
- 429006000000  天门市
- 429021000000  神农架林区

**Comment by jaywcjlove** [comment]
@fjc0k 省市区数据是通过 http://www.mca.gov.cn/article/sj/xzqh/2020/2020/2020112010001.html 直接一次获取全部的数据。

**Comment by jaywcjlove** [comment]
@fjc0k  通过获取的`省市区`数据，再去 http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/index.html 去获取 `乡级(乡镇/街)`, `省/地/县/乡层级数据`

**Comment by fjc0k** [comment]
@jaywcjlove 那是在 level 包里缺了，最近做这个发现和微信的对不上，一看 level 里就缺这几个：

https://unpkg.com/@province-city-china/level@7.1.1/level.json

**Comment by jaywcjlove** [comment]
@fjc0k 在这个 [`全国统计用区划代码和城乡划分代码的公告`](http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/index.html) 数据是放在 `省直辖县级行政区划`

[省市区](http://www.mca.gov.cn/article/sj/xzqh/2020/2020/2020112010001.html) 数据是放在 `恩施土家族苗族自治州` 下面，以哪个为准呢？

```json
{
  "code": "422800",
  "name": "省直辖县级行政区划",
  "province": "42",
  "city": "90",
  "children": [
    {
      "code": "429004",
      "name": "仙桃市",
      "province": "42",
      "city": "90",
      "area": "04"
    },
    {
      "code": "429005",
      "name": "潜江市",
      "province": "42",
      "city": "90",
      "area": "05"
    },
    {
      "code": "429006",
      "name": "天门市",
      "province": "42",
      "city": "90",
      "area": "06"
    },
    {
      "code": "429021",
      "name": "神农架林区",
      "province": "42",
      "city": "90",
      "area": "21"
    }
  ]
}
```

**Comment by jaywcjlove** [comment]
参考高德地图，将放置 `湖北省` 下面

**Comment by fjc0k** [comment]
微信小程序的是放在 `省直辖县级行政区划` 下的：

![image](https://user-images.githubusercontent.com/13151189/105795709-3c9dbb00-5fc8-11eb-84cb-d15aa35a9543.png)

**Comment by jaywcjlove** [comment]
@fjc0k Upgrade `7.1.2`


| 包名 | 说明  | 版本 | 大小 |
| ---- | ---- | ---- | ---- |
| [province-city-china](https://github.com/uiwjs/province-city-china) | 包含所有包内容 | [![npm package](https://img.shields.io/npm/v/province-city-china.svg)](https://www.npmjs.com/package/province-city-china) | - |
| [@province-city-china/country](packages/country) | 国家和地区代码列表 | [![npm package](https://img.shields.io/npm/v/@province-city-china/country.svg)](https://www.npmjs.com/package/@province-city-china/country) |![](https://img.shields.io/bundlephobia/min/@province-city-china/country) |
| [@province-city-china/data](packages/data) | 总数据(省/地/县/乡) | [![npm package](https://img.shields.io/npm/v/@province-city-china/data.svg)](https://www.npmjs.com/package/@province-city-china/data) | ![](https://img.shields.io/bundlephobia/min/@province-city-china/data) |
| [@province-city-china/province](packages/province) | 省级(省/直辖市/特别行政区) | [![npm package](https://img.shields.io/npm/v/@province-city-china/province.svg)](https://www.npmjs.com/package/@province-city-china/province) | ![](https://img.shields.io/bundlephobia/min/@province-city-china/province) |
| [@province-city-china/city](packages/city) | 地级(城市) | [![npm package](https://img.shields.io/npm/v/@province-city-china/city.svg)](https://www.npmjs.com/package/@province-city-china/city) | ![](https://img.shields.io/bundlephobia/min/@province-city-china/city) |
| [@province-city-china/area](packages/area) | 县级(区县) | [![npm package](https://img.shields.io/npm/v/@province-city-china/area.svg)](https://www.npmjs.com/package/@province-city-china/area) | ![](https://img.shields.io/bundlephobia/min/@province-city-china/area) |
| [@province-city-china/town](packages/town) | 乡级(乡镇/街) | [![npm package](https://img.shields.io/npm/v/@province-city-china/town.svg)](https://www.npmjs.com/package/@province-city-china/town) | ![](https://img.shields.io/bundlephobia/min/@province-city-china/town) |
| [@province-city-china/level](packages/level) | 总数据(省/地/县/乡)层级数据 | [![npm package](https://img.shields.io/npm/v/@province-city-china/level.svg)](https://www.npmjs.com/package/@province-city-china/level) | ![](https://img.shields.io/bundlephobia/min/@province-city-china/level) |
| [@province-city-china/utils](packages/utils) | 提供使用数据方法 | [![npm package](https://img.shields.io/npm/v/@province-city-china/utils.svg)](https://www.npmjs.com/package/@province-city-china/utils) | ![](https://img.shields.io/bundlephobia/min/@province-city-china/utils) |

**Comment by fjc0k** [comment]
@jaywcjlove 👍
