### ISSUE TITLE
掘金上看到兄弟的这个干货，省了俺很多时间，有个问题

### ISSUE THREAD

**Issue by jhyc** [uiwjs/province-city-china#2]
掘金上看到兄弟的这个干货，省了俺很多时间，有个问题想请教一把：以后像区，镇之类有新增了，如何进行增量维护呢？
现在头一次用可以直接把那个data.sql直接入表就行了，但以后有了新的区，镇就不能删了表重新导入啦，怎么增量处理呢？

**Comment by jaywcjlove** [comment]
@jhyc 存在更新和变更，

用 `code` 做索引比较好，不能用自增长ID，`code` 做索引，对于新增应该没有什么大问题，对于变更，可能你需要写脚本去更新你的数据，回头有更新，看能不能写脚本来变更。
