### ISSUE TITLE
地区区号？

### ISSUE THREAD

**Issue by vinurs** [uiwjs/province-city-china#23]
考虑不考虑加上这些信息
1. 地区的区号 010， 021
2. 地区的简称，例如京、津
3. 车牌号，沪A、沪B

**Comment by jaywcjlove** [comment]
@vinurs 有想法可以加上的，区号不用加吧里面不是有？

地区的简称，车牌号 这些可以单独发包吧。

**Comment by vinurs** [comment]
@jaywcjlove 区号是哪个字段啊，我貌似没找到啊

**Comment by jaywcjlove** [comment]
@vinurs 区号好像没有，这个数据可以爬一下

http://www.gov.cn/gzdt/2010-01/15/content_1511043.htm

**Comment by jaywcjlove** [comment]
已添加使用 `@province-city-china/district-code` 包或者 `province-city-china` 包中的数据。

**Comment by jaywcjlove** [comment]
放在一起体积太大，分包，你可以自己合并数据。
