### ISSUE TITLE
什么时候可以把澳门、台湾、香港信息补全？

### ISSUE THREAD

**Issue by lidope** [uiwjs/province-city-china#24]
体验感很不好哦

**Comment by jaywcjlove** [comment]
@lidope 哪里有香港澳门比较官方的信息，我去爬一下

**Comment by lidope** [comment]
我也不知道哇



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小弟调调™ ***@***.***&gt;
发送时间: 2021年7月25日 23:26
收件人: uiwjs/province-city-china ***@***.***&gt;
抄送: lidope ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[uiwjs/province-city-china] 什么时候可以把澳门、台湾、香港信息补全？ (#24)





 
@lidope 哪里有香港澳门比较官方的信息，我去爬一下

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/province-city-china/issues/14

@lidope 已经加入香港澳门数据，~~`台湾`~~数据目前没有找到比较官方的数据
