### ISSUE TITLE
level.min.json缺失

### ISSUE THREAD

**Issue by yoyocheung914** [uiwjs/province-city-china#25]
level.min.json什么时候东莞市，中山市，三沙市，儋州市，嘉峪关市的镇数据补上

**Comment by jaywcjlove** [comment]
`东莞市`，`中山市`，`三沙市`，`儋州市`，`嘉峪关市` 是直辖市。

下面的数据是<街道>码，所以你需要使用街道数据，自己手动添加到 `东莞市`层级下。

@yoyocheung914
