### ISSUE TITLE
level 缺少海南省的469000000000	省直辖县级行政区划

### ISSUE THREAD

**Issue by tonyliving** [uiwjs/province-city-china#27]
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/46.html

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/140009043-a7254a37-8714-4206-b3bd-4e422a8da81e.png)

https://unpkg.com/province-city-china@8.0.0/dist/data.json

@tonyliving

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/140009109-d3efe0aa-0850-4466-8e03-e7b214a971c9.png)

https://unpkg.com/province-city-china@8.0.0/dist/level.json

@tonyliving

**Comment by tonyliving** [comment]
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/46/4690.html 这个都没了啊
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2020/46.html 这个里面的省直辖县级行政区划

**Comment by tonyliving** [comment]
比如五指山市

**Comment by tonyliving** [comment]
@jaywcjlove

**Comment by jaywcjlove** [comment]
@tonyliving 正在爬了，在 #34 中解决。
