### ISSUE TITLE
中山市数据不全

### ISSUE THREAD

**Issue by tianlunshu** [uiwjs/province-city-china#4]
国家统计局里面中山市下的街道数据在data.csv里面没有，补充下

**Comment by jaywcjlove** [comment]
@tianlunshu 正在爬新的数据，我在对照着看看。

**Comment by tomsunwolf** [comment]
我下载了data.sql文件，如何导入mysql数据库啊？使用了mqsql的数据导入功能，不正常，打开源代码看看感觉是html文件呢

**Comment by jaywcjlove** [comment]
@tomsunwolf 啥意思？

**Comment by tomsunwolf** [comment]
我再其他网址看到后，下载了该网站提供的本项目的全部地址的data.sql数据库文件，但无法导入mysql数据库？使用了mqsql的数据导入功能，不正常，打开这个data.sql文件的源代码看看感觉是html文件，这个应该没有办法导入mysql吧？哪一个文件可以导入进mysql数据库呢？

**Comment by jaywcjlove** [comment]
@tomsunwolf 这是个 [data.sql](https://unpkg.com/province-city-china/dist/data.sql) 文本，你下载下来找个工具执行一下就行了

**Comment by jaywcjlove** [comment]
@tomsunwolf 或者你clone 下来，里面就有  `.sql` 文件
