### ISSUE TITLE
Typescript 声明类型时似乎未能得到完整支持？

### ISSUE THREAD

**Issue by fjqingyou** [uiwjs/province-city-china#40]
``` typescript
import ProvinceCityChina from "province-city-china";

export class Test{
    protected provinceObj : ProvinceCityChina.Province | null = null;//命名空间“"province-city-china"”没有已导出的成员“Province”。ts(2694)
}
```

请问是否我的用法有误？

**Comment by fjqingyou** [comment]
如果是在 nodejs 环境下倒是可以用
```
export class Test{
    protected provinceObj : globalThis.ProvinceCityChina.Province | null = null;
}
```
这种方式声明，不过这样它就附带了个 globalThis 的前缀，会降低代码的移植性。请问是否有更合适的使用方式？

**Comment by jaywcjlove** [comment]
@fjqingyou 我测试下来没有问题呢。

![image](https://user-images.githubusercontent.com/1680273/195353322-56e804fe-14e3-4e47-8de0-a83be00ccaba.png)

没有默认到出方法，需要下面方式导入包？

```js
import data from 'province-city-china'
import dataCity from  'province-city-china/dist/city.json'
```

![image](https://user-images.githubusercontent.com/1680273/195353389-01b3ae70-64ac-4a9e-8600-11c08831dfde.png)

**Comment by jaywcjlove** [comment]
@fjqingyou Upgrade `v8.5.2` 

```ts
import { City } from 'province-city-china'

import type ProvinceCityChina from '@province-city-china/types'

const data: Partial<City> = { code: '12', name: 'dsfsdf'}
const dt: Partial<ProvinceCityChina.Area> = {}
```

**Comment by fjqingyou** [comment]
我在 vscode 中新建了一个 Test.ts ，复制了这个例子后，似乎并未按预期工作。是否是我的用法错误？


![image](https://user-images.githubusercontent.com/31087168/195377008-e6705595-5dce-41fa-9cdf-73d4b516a2c8.png)

**Comment by jaywcjlove** [comment]
@fjqingyou  Upgrade v8.5.4, 找到原因了，修复了。

**Comment by fjqingyou** [comment]
已经按预期工作，感谢！

**Comment by fjqingyou** [comment]
@jaywcjlove 似乎 Country 类型的并未被导出？

**Comment by fjqingyou** [comment]
@jaywcjlove 它正常工作了！感谢！
