### ISSUE TITLE
关于数据维护

### ISSUE THREAD

**Issue by WankkoRee** [uiwjs/province-city-china#48]
我看历史 commit 中，对于一些行政区划变更，是直接删除旧代码添加新代码，这种方法大部分时候会导致基于此库的代码发生异常。

一个合理的方案应当为添加一个`deprecated`字段用来标记这个行政区划已经不应该再使用。

**Comment by jaywcjlove** [comment]
<img width="530" alt="image" src="https://github.com/uiwjs/province-city-china/assets/1680273/0b4d4142-e9ee-433c-ae7a-3e001e90d12b">

@WankkoRee 也没有直接删除维护了这么一个数据

**Comment by jaywcjlove** [comment]
<img width="633" alt="image" src="https://github.com/uiwjs/province-city-china/assets/1680273/7f21e38a-0254-4900-9818-59b68ca7151d">
