### ISSUE TITLE
压缩数据说明错误

### ISSUE THREAD

**Issue by threeStepWalk** [uiwjs/province-city-china#49]
@province-city-china 包中 readme 压缩数据说明 city 为 y ，但实际 level.min.json 中 city 为 d
![image](https://github.com/uiwjs/province-city-china/assets/40707695/a10ecd12-5047-4f79-81d9-64cc0af2270e)
![image](https://github.com/uiwjs/province-city-china/assets/40707695/fbb726a3-5498-4b3c-8958-821cf6b51e28)

**Comment by jaywcjlove** [comment]
@threeStepWalk 已经修复，更新 `v8.5.7`, `city` 数据更改为 `y`,  `d` 与数据 `children`

**Comment by jaywcjlove** [comment]
@threeStepWalk 已经修复，更新 `v8.5.7`, `city` 数据更改为 `y`,  `d` 与数据 `children` 冲突
