### ISSUE TITLE
香港台湾澳门被列为国家？不妥吧

### ISSUE THREAD

**Issue by chenyuncai** [uiwjs/province-city-china#55]

**Comment by jaywcjlove** [comment]
@chenyuncai 没有说她是国家，是 `国家和地区`，他是个中国地区

**Comment by jaywcjlove** [comment]
<img width="193" alt="image" src="https://github.com/user-attachments/assets/23c7975f-bc6a-4a3b-bf5a-969efa0e743a">

**Comment by jaywcjlove** [comment]
@chenyuncai 检查了半天，也没有看到描述`香港台湾澳门` 为国家的地方

**Comment by chenyuncai** [comment]
https://github.com/uiwjs/province-city-china/blob/master/packages/core/dist/country.json
![Screenshot_2024-09-05-15-40-25-905_com microsoft emmx](https://github.com/user-attachments/assets/25af4143-2130-40d7-8f96-c528dabe169a)

**Comment by chenyuncai** [comment]
我是因为用了插件，下拉框里发现了数据 然后再来看代码里，确实找到了的，country json

**Comment by jaywcjlove** [comment]
@chenyuncai 这个是国家和地区，之前是从政府网站网站上爬下来的，他们把这个描述成`国家和地区`，我把这个文件名改成`国家和地区`

**Comment by jaywcjlove** [comment]
算球直接移除吧 @chenyuncai

**Comment by jaywcjlove** [comment]
@chenyuncai 这个数据是从中国政府网站上爬下来的，数据上有 `of China` 描述

**Comment by chenyuncai** [comment]
感谢感谢
